spring:
  profiles:
    active: local
    group:
      local: local, common, secret, aws
      blue: blue, common, secret, aws


server:
  env: blue

---
spring:
  config:
    activate:
      on-profile: local

server:
  port: 8080
  serverAddress: localhost
  serverName: todayclothes

---
spring:
  config:
    activate:
      on-profile: blue

server:
  port: 8080
  serverAddress: 43.201.243.237
  serverName: blue_server

---

spring:
  config:
    activate:
      on-profile: common
  jpa:
    hibernate:
      ddl-auto: create
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect