spring:
  profiles:
    active: blue

server:
  env: blue

---
spring:
  config:
    activate:
      on-profile: blue

server:
  port: 8080
  serverAddress: 15.165.60.191
  serverName: blue_server

---
spring:
  config:
    activate:
      on-profile: common
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

